name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Release
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yaml
          miniconda-version: latest
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - uses: sonarsource/sonarqube-scan-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Package
        run: make package
      - name: Validate
        run: make validate
      - name: Release
        run: make release
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: https://repo.devops.projectronin.io/repository/ronin-pypi/
