name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Release
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yaml
          miniconda-version: latest
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Package
        run: make package
      - name: Validate
        run: make validate
      - name: Release
        run: make release
        env:
          TWINE_USERNAME: ${{ secrets.NEXUS_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.NEXUS_PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: https://repo.devops.projectronin.io/repository/ronin-pypi/
