name: Rename
on:
  push:
    branches:
      - main
jobs:
  rename:
    if: ${{ !contains (github.repository, '/ronin-blueprint-python-lib') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Create package name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]' | sed "s/.*lib-//g")" >> $GITHUB_ENV
        shell: bash
      - name: Create python name
        run: echo "PYTHON_NAME=$(echo '${{ env.REPOSITORY_NAME }}' | sed "s/-/_/g")" >> $GITHUB_ENV
        shell: bash
      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/workflows/rename.yaml &> /dev/null && echo true || echo false)"
      - name: Rename the package
        if: steps.is_template.outputs.is_template == 'true'
        run: git grep -rl hello-world -- './*' ':!.github/**' | xargs sed -i  "s/hello-world/${{ env.REPOSITORY_NAME }}/g"
        shell: bash
      - name: Rename python imports
        if: steps.is_template.outputs.is_template == 'true'
        run: git grep -rl hello_world -- './*' ':!.github/**' | xargs sed -i  "s/hello_world/${{ env.PYTHON_NAME }}/g"
        shell: bash
      - name: Rename python source library
        if: steps.is_template.outputs.is_template == 'true'
        run: mv src/hello_world "src/${{ env.PYTHON_NAME }}" && mv tests/test_hello_world.py "tests/test_${{ env.PYTHON_NAME }}.py"
        shell: bash
      - name: Remove workflow when done
        if: steps.is_template.outputs.is_template == 'true'
        run: rm .github/workflows/rename.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Rename Template References"
          branch: rename
          delete-branch: true
          body: |
            - Auto-generated by [create-pull-request][1] from the [template rename action][2]
            [1]: https://github.com/peter-evans/create-pull-request
            [2]: https://github.com/projectronin/ronin-blueprint-python-lib/blob/main/.github/workflows/rename.yaml
          draft: false
